//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentTweet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentTweet()
        {
            this.CommentReplies = new HashSet<CommentReply>();
        }
    
        public int CommentId { get; set; }
        public Nullable<int> TweetId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string CommentText { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual UsersTweet UsersTweet { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentReply> CommentReplies { get; set; }
    }
}
